In [3]:
import numpy as np

In [72]:
#Создать одномерный массив Numpy
a = np.arange(12, 24)
a
a.shape

(12,)

In [15]:
#Создать 5 двумерных массивов разной формы
b = a[:,np.newaxis]
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [16]:
b.shape

(12, 1)

In [31]:
c = np.where(a != 0, 2 / a, a)
c = c[np.newaxis,:]
c

array([[0.16666667, 0.15384615, 0.14285714, 0.13333333, 0.125     ,
        0.11764706, 0.11111111, 0.10526316, 0.1       , 0.0952381 ,
        0.09090909, 0.08695652]])

In [32]:
c.shape

(1, 12)

In [37]:
d = np.where(a != 0, 3 / a, a)
d = d[np.newaxis,:]
d

array([[0.25      , 0.23076923, 0.21428571, 0.2       , 0.1875    ,
        0.17647059, 0.16666667, 0.15789474, 0.15      , 0.14285714,
        0.13636364, 0.13043478]])

In [35]:
d.shape

(1, 12)

In [41]:
f = np.add(a, a)
f = f[np.newaxis,:]
f.shape

(1, 12)

In [48]:
#Использовать в аргументах метода reshape число -1
b1 = np.reshape(a, (2, -1))
b1.shape

(2, 6)

In [59]:
c1 = np.reshape(a, (-1, 3))
c1.shape

(4, 3)

In [63]:
d1 = np.reshape(a, (-1, 1))
d1.shape

(12, 1)

In [71]:
f1 = np.reshape(a, (4, -1))
f1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [73]:
f1.shape

(4, 3)

In [74]:
#Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным
#Ответ: Да, можно

In [88]:
#Создать массив из 3 строк и 4 столбцов
ab = np.random.sample((4, 3))
ab.size

12

In [89]:
ac = ab.flatten()
ac.size

12

In [93]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [102]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2
b = np.linspace(20, 1, num=10, endpoint=False, retstep=2, dtype=int)
b
#Ответ: Разница в методе создания массивов, впервом случае я использовал arange 
#во втором можно было использовать только linspace с его допольнительными атрибутами, шаг 2 только неполучился из-за "1"

(array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2]), -1.9)

In [123]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей b, состоящего из единиц.
a = np.zeros((2, 2))
b = np.ones((3, 2))
#a.transpose()


In [124]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [125]:
v.size

10

In [129]:
#9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
A = np.arange(0, 12).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [130]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [132]:
B = np.dot(A, At)
B.size
#Размер матрице B 16

16

In [136]:
B_inv = np.linalg.inv(B)
#Выдается ошибка что матрица сингулярна, почитал, нашел: Сингулярная матрица - это та, которая не обратима
#но мне пока такое сложно понять)

In [152]:
np.random.seed(42)


In [157]:
#Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых
c = np.random.randint(0, 15, 16)
c

array([11, 12,  7, 14,  2, 13,  0,  3,  1,  7,  3,  1, 13,  5,  5,  9])

In [160]:
c1 = np.reshape(c, (4, 4))
c1 #c1 - это матрица C

array([[11, 12,  7, 14],
       [ 2, 13,  0,  3],
       [ 1,  7,  3,  1],
       [13,  5,  5,  9]])

In [162]:
D = np.add(B, c1)
D = np.dot(10, D)
D

array([[ 160,  260,  300,  460],
       [ 160,  630,  860, 1250],
       [ 240,  930, 1520, 2130],
       [ 450, 1270, 2170, 3110]])

In [163]:
np.linalg.det(D) #вычисления определителя

1282279999.9999952

In [164]:
np.linalg.matrix_rank(D) # вычисление ранга

4

In [166]:
D_inv = np.linalg.inv(D) #Вычисление обратной матрицы
D_inv

array([[ 0.01157781, -0.00897464,  0.0039461 , -0.00080794],
       [ 0.00372618,  0.00419097,  0.00382288, -0.00485385],
       [ 0.01672802, -0.02557632,  0.03074524, -0.0132514 ],
       [-0.01486883,  0.01743301, -0.02358455,  0.01166672]])